import 'package:animate_do/animate_do.dart';
import 'package:car/core/cache/hive/hive_methods.dart';
import 'package:car/core/localization/app_locale_keys.dart';
import 'package:car/core/theme/app_colors.dart';
import 'package:car/core/theme/app_text_style.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:gap/gap.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class CarComparisonScreen extends StatefulWidget {
  const CarComparisonScreen({super.key});

  @override
  State<CarComparisonScreen> createState() => _CarComparisonScreenState();
}

class _CarComparisonScreenState extends State<CarComparisonScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColor.scaffoldColor(context),
      appBar: AppBar(
        title: Text(
          AppLocaleKey.comparisonTitle.tr(),
          style: AppTextStyle.titleMedium(context).copyWith(fontWeight: FontWeight.bold),
        ),
        backgroundColor: AppColor.appBarColor(context),
        elevation: 0,
        actions: [
          ValueListenableBuilder(
            valueListenable: Hive.box('app').listenable(keys: ['comparisonList']),
            builder: (context, box, _) {
              final list = box.get('comparisonList', defaultValue: []);
              if (list.isEmpty) return const SizedBox.shrink();
              return IconButton(
                onPressed: () => HiveMethods.clearComparisonList(),
                icon: Icon(Icons.delete_outline_rounded, color: AppColor.redColor(context)),
                tooltip: AppLocaleKey.clearHistory.tr(),
              );
            },
          ),
        ],
      ),
      body: ValueListenableBuilder(
        valueListenable: Hive.box('app').listenable(keys: ['comparisonList']),
        builder: (context, box, _) {
          final list = box.get('comparisonList', defaultValue: []) as List;
          if (list.isEmpty) return _buildEmptyState();
          return _buildComparisonGrid(list);
        },
      ),
    );
  }

  Future<void> _generatePdf(List<dynamic> list) async {
    final pdf = pw.Document();

    final specs = [
      {'key': 'Engine', 'field': 'engine'},
      {'key': 'Horsepower', 'field': 'horsepower'},
      {'key': 'Transmission', 'field': 'transmission'},
      {'key': 'Fuel Type', 'field': 'fuel_type'},
      {'key': 'Drivetrain', 'field': 'drivetrain'},
    ];

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) => [
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Car Comparison Report',
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
                ),
                pw.Text(DateFormat('yyyy-MM-dd').format(DateTime.now())),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          pw.TableHelper.fromTextArray(
            headers: ['Spec', ...list.map((c) => c['name'])],
            data: specs
                .map((spec) => [spec['key']!, ...list.map((c) => c[spec['field']] ?? 'N/A')])
                .toList(),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
            cellAlignment: pw.Alignment.centerLeft,
          ),
          pw.SizedBox(height: 40),
          pw.Footer(
            title: pw.Text(
              'Generated by Car App - Elite Rewards Edition',
              style: const pw.TextStyle(color: PdfColors.grey700),
            ),
          ),
        ],
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: 'car_comparison.pdf');
  }

  Widget _buildEmptyState() {
    return Center(
      child: FadeInUp(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.compare_arrows_rounded, size: 80.sp, color: AppColor.hintColor(context)),
            Gap(16.h),
            Text(
              AppLocaleKey.comparisonEmpty.tr(),
              style: AppTextStyle.bodyLarge(context).copyWith(color: AppColor.greyColor(context)),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildComparisonGrid(List<dynamic> list) {
    return SingleChildScrollView(
      padding: EdgeInsets.all(16.w),
      child: Column(
        children: [
          // Sticky Car Headers Row
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: list
                .map(
                  (car) => Expanded(
                    child: Padding(
                      padding: EdgeInsets.symmetric(horizontal: 4.w),
                      child: _buildCarColumn(car),
                    ),
                  ),
                )
                .toList(),
          ),
          Gap(24.h),
          // Specs Table
          _buildSpecsTable(list),
          Gap(40.h),
          // Download/Share Button
          FadeInUp(
            delay: const Duration(milliseconds: 500),
            child: SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: () => _generatePdf(list),
                icon: const Icon(Icons.picture_as_pdf_rounded),
                label: Text(AppLocaleKey.downloadComparison.tr()),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColor.primaryColor(context),
                  foregroundColor: Colors.white,
                  padding: EdgeInsets.symmetric(vertical: 16.h),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12.r)),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildCarColumn(Map<dynamic, dynamic> car) {
    return Column(
      children: [
        Stack(
          children: [
            Container(
              height: 100.h,
              decoration: BoxDecoration(
                color: AppColor.cardColor(context),
                borderRadius: BorderRadius.circular(12.r),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.05),
                    blurRadius: 10,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: Center(child: Image.asset(car['image'], fit: BoxFit.contain)),
            ),
            Positioned(
              top: 4,
              right: 4,
              child: GestureDetector(
                onTap: () {
                  HiveMethods.removeFromComparison(car['name']);
                },
                child: Container(
                  padding: const EdgeInsets.all(2),
                  decoration: const BoxDecoration(color: Colors.red, shape: BoxShape.circle),
                  child: const Icon(Icons.close, color: Colors.white, size: 14),
                ),
              ),
            ),
          ],
        ),
        Gap(8.h),
        Text(
          car['name'],
          textAlign: TextAlign.center,
          maxLines: 2,
          overflow: TextOverflow.ellipsis,
          style: AppTextStyle.bodyMedium(context).copyWith(fontWeight: FontWeight.bold),
        ),
        Gap(4.h),
        Text(
          car['price'],
          style: AppTextStyle.bodySmall(
            context,
          ).copyWith(color: AppColor.primaryColor(context), fontWeight: FontWeight.bold),
        ),
      ],
    );
  }

  Widget _buildSpecsTable(List<dynamic> list) {
    final specs = [
      {'key': 'Engine', 'field': 'engine'},
      {'key': 'Horsepower', 'field': 'horsepower'},
      {'key': 'Transmission', 'field': 'transmission'},
      {'key': 'Fuel Type', 'field': 'fuel_type'},
      {'key': 'Drivetrain', 'field': 'drivetrain'},
    ];

    return Container(
      decoration: BoxDecoration(
        color: AppColor.cardColor(context),
        borderRadius: BorderRadius.circular(12.r),
        border: Border.all(color: AppColor.dividerColor(context)),
      ),
      child: Column(
        children: specs.map((spec) {
          return Container(
            padding: EdgeInsets.symmetric(vertical: 12.h, horizontal: 12.w),
            decoration: BoxDecoration(
              border: spec == specs.last
                  ? null
                  : Border(bottom: BorderSide(color: AppColor.dividerColor(context))),
            ),
            child: Row(
              children: [
                ...list.map(
                  (car) => Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        if (list.indexOf(car) == 0)
                          Text(
                            spec['key']!,
                            style: AppTextStyle.bodySmall(
                              context,
                            ).copyWith(color: AppColor.greyColor(context), fontSize: 10.sp),
                          ),
                        Text(car[spec['field']] ?? 'N/A', style: AppTextStyle.bodyMedium(context)),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}
